version: '3'
services:
  backend:
    image: planobordo:latest
    container_name: plano-bordo-backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/web